/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ashishw' at '28/2/16 12:46 AM' with Gradle 2.2.1
 *
 * @author ashishw, @date 28/2/16 12:46 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
